ERROR: Exception caught trying to open file D:\xilinx_projects\16_ov5640_single\ov5640_single.runs\system_auto_us_4_synth_1/runme.log
	Exception name: Error
	Exception error code: 70
	Exception message: 没有权限
